### ISSUE TITLE
Add info of the sponsorship packages

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#156]
The website doesn't have any information about the costs of the sponsorships and the benefits.

**Comment by marcoscano** [comment]
As far as I understand from https://trello.com/c/pA0IRFd2 this is still pending content validation, isn't it?

Here is the page that was used last year, if it serves as a reference:
http://2015.drupalcamp.es/es/drupalcamp-spain-2015/sponsors/patrocinios

**Comment by DavidHernandez** [comment]
It's approved now.

**Comment by marcoscano** [comment]
I have just checked the node (non-published), and updated the table to match the googledoc proposal (referred on the trello task).

I have left it unpublished because the PDF attached to it refers to the 2015 edition. I don't know if there is an equivalent document for 2016, or if this will be deleted this year.

**Comment by plopesc** [comment]
I reviewed and published the content
